name: example
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  dio:
  source_gen: ^1.1.0
  build_config:
  build_runner:
  presenter: 
    path: ../presenter

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  presenter_generator: 
    path: ../presenter_generator
