builders:
  mock_builder:
    import: "package:mock_generator/mock_generator.dart"
    builder_factories: ["generateMocks"]
    build_extensions: {'.dart': ['.mock.dart']}
    auto_apply: dependents
    build_to: source
    defaults:
      options:
        build_extensions:
          '^lib/{{}}.dart': 'lib/mocks/generated/{{}}.mock.dart'

  mock_library_builder:
    import: "package:mock_generator/mock_generator.dart"
    builder_factories: ["generateMocksLibrary"]
    build_extensions: {'$lib$': ['mocks/mocks.dart']}
    auto_apply: dependents
    build_to: source


  
  
