name: mock_generator
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  build: 
  analyzer: 5.1.0 
  source_gen: ^1.1.0
  mock: 
    path: ../mock/


dev_dependencies:
  build_test:
  build_runner:
  lints: 2.0.0
  build_config:


