builders:
  mock_builder:
    import: "package:presenter_generator/testable_generator.dart"
    builder_factories: ["generateExecutor"]
    build_extensions: {'.dart': ['.mock.dart']}
    auto_apply: dependents
    build_to: source
    defaults:
      options:
        build_extensions:
          '^lib/{{}}.dart': 'lib/generated/{{}}.g.dart'

  
  
