name: presenter_generator
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  build: 
  source_gen: 
  analyzer: 5.1.0 
  presenter: 
    path: ../presenter/


dev_dependencies:
  build_test:
  build_runner:
  lints: 2.0.0

